"""init

Revision ID: 456b9ad433e2
Revises: 
Create Date: 2025-02-03 18:10:17.151610

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "456b9ad433e2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("chats",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("username", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("username"),
    )
    op.create_table("chat_users",
    sa.Column("chat_id", sa.Integer(), nullable=True),
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_table("messages",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("text", sa.String(), nullable=False),
    sa.Column("chat_id", sa.Integer(), nullable=False),
    sa.Column("sender_id", sa.Integer(), nullable=False),
    sa.Column("receiver_id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["receiver_id"], ["users.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_table("chat_users")
    op.drop_table("users")
    op.drop_table("chats")
    # ### end Alembic commands ###
