"""simplify_messages_table

Revision ID: 5fbb731927b2
Revises: 456b9ad433e2
Create Date: 2025-02-04 07:19:55.187829

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5fbb731927b2"
down_revision: Union[str, None] = "456b9ad433e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    op.drop_column("messages", "updated_at")
    op.drop_column("messages", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), autoincrement=False, nullable=True))
    op.add_column("messages", sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column("messages", "timestamp")
    # ### end Alembic commands ###
